name: 'TEST GitHub Actions Scan'

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  test-zizmor-scan:
    uses: './.github/workflows/github_actions_scan.yml'
    with:
      wif_provider: 'projects/763312321262/locations/global/workloadIdentityPools/gitsec-gha-artifacts/providers/gitsec-gha-artifacts-provider'
      zizmor_result_bucket: 'zizmor-43e4'
      zizmor_config_bucket: 'zizmor-configs-06f3'
      zizmor_enforce: 'false'
